type ReputationData = {
  wallet: string;
  role: string;
  membership: {
    role: string;
    score: number;
  };
  totalReputation: number;
  level: {
    level: number;
    title: string;
  };
  badges: {
    name: string;
    description: string;
  }[];
  contributor: {
    displayName: string;
    username: string;
    walletAddress: string;
    profileImage: string;
    membershipType: string;
    verified: boolean;
    accountStatus: string;
    country: string;
    category: string;
  };
  profileCompletion: number;
  daoVotingWeight: number;
  breakdown: {
    membership: number;
    contributor: number;
    opportunities: number;
    rewards: number;
  };
  history: {
    title: string;
    reputation: number;
  }[];
};

type Props = {
  data: ReputationData;
};

import ReputationBreakdown from "./ReputationBreakdown";
import ReputationHistory from "./ReputationHistory";

export default function ContributorDetails({
  data,
}: Props) {
  return (
    <section className="rounded-2xl border border-zinc-800 bg-zinc-900">
      <div className="border-b border-zinc-800 p-6">
        <h2 className="text-2xl font-bold text-white">
          Contributor Reputation
        </h2>

        <p className="mt-1 text-sm text-zinc-400">
          Complete reputation profile generated by the reputation engine.
        </p>
      </div>

      <div className="grid gap-8 p-6 lg:grid-cols-2">

        <div className="space-y-6">

          <div>

            <h3 className="mb-4 text-lg font-semibold text-white">
              Contributor
            </h3>

            <div className="space-y-2 text-sm">

              <p>
                <span className="text-zinc-400">Display Name:</span>{" "}
                <span className="text-white">
                  {data.contributor.displayName}
                </span>
              </p>

              <p>
                <span className="text-zinc-400">Username:</span>{" "}
                <span className="text-white">
                  @{data.contributor.username}
                </span>
              </p>

              <p>
                <span className="text-zinc-400">Wallet:</span>{" "}
                <span className="text-white">
                  {data.wallet}
                </span>
              </p>

              <p>
                <span className="text-zinc-400">Country:</span>{" "}
                <span className="text-white">
                  {data.contributor.country || "-"}
                </span>
              </p>

              <p>
                <span className="text-zinc-400">Category:</span>{" "}
                <span className="text-white">
                  {data.contributor.category || "-"}
                </span>
              </p>

            </div>

          </div>

          <div>

            <h3 className="mb-4 text-lg font-semibold text-white">
              Reputation
            </h3>

            <div className="grid grid-cols-2 gap-4">

              <Metric
                title="Total Reputation"
                value={data.totalReputation}
              />

              <Metric
                title="Level"
                value={data.level.title}
              />

              <Metric
                title="DAO Weight"
                value={data.daoVotingWeight}
              />

              <Metric
                title="Completion"
                value={`${data.profileCompletion}%`}
              />

            </div>

          </div>

          <div>

            <h3 className="mb-4 text-lg font-semibold text-white">
              Badges
            </h3>

            <div className="flex flex-wrap gap-2">

              {data.badges.map((badge) => (
                <span
                  key={badge.name}
                  className="rounded-full bg-blue-600/20 px-3 py-1 text-sm text-blue-300"
                >
                  {badge.name}
                </span>
              ))}

              {data.badges.length === 0 && (
                <span className="text-zinc-500">
                  No badges awarded.
                </span>
              )}

            </div>

          </div>

        </div>

        <div className="space-y-6">

          <ReputationBreakdown
            breakdown={data.breakdown}
          />

          <ReputationHistory
            history={data.history}
          />

        </div>

      </div>
    </section>
  );
}

function Metric({
  title,
  value,
}: {
  title: string;
  value: string | number;
}) {
  return (
    <div className="rounded-xl border border-zinc-800 bg-zinc-950 p-4">
      <p className="text-xs uppercase tracking-wide text-zinc-500">
        {title}
      </p>

      <p className="mt-2 text-xl font-bold text-white">
        {value}
      </p>
    </div>
  );
}